import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Card from "@/components/ui/Card";
import homePageCards from "../data/homePageCards.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cruxer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <section className={`${styles.home_section} py-4 text-center rounded-3`}>
        <div className="container">
          <h1 className="display-4 fw-bold">C R U <span className={`${styles.title_x}`}>&#10007;</span> E R</h1>
          <h3 className="display-8 mb-4">
            {"Cruxer is the ultimate social app for climbers. Track your ascents, connect with other climbers, and discover new routes — all in one place."}
          </h3>
          <Link href="/auth/signup" className={`${styles.link} px-5 py-2 mt-4 fw-bold`}>Join the Community</Link>
        </div>
      </section>

      <section className="row mt-2 g-4 mb-4">
        {homePageCards.map((card, index) => (
          <div key={index} className="col-12 col-md-4 card-group">
            <Card
              title={card.title}
              description={card.description}
              link={card.link}
              image={card.image}
            />
          </div>
        ))}
      </section>

      <section className={`${styles.home_section} py-4 text-center rounded-3`}>
        <div className="container">
          <h3 className="display-8">
            {"Don't Just Climb. Cruxer It."}
          </h3>
          <p>
            {"Sure, you could keep logging your climbs in a dusty notebook or that weird spreadsheet with 14 tabs... but why not level up?"}
            {"With Cruxer, you're not just tracking ascents — you're high-fiving after sends, swapping beta with climbers across the globe, and discovering epic routes you didn't even know existed. Whether you're crushing plastic at the gym, dancing up sandstone, or flailing (respectfully) on your latest project, Cruxer's got your back."}
          </p>
          <p className="fw-bold mb-0">
            {"Connect. Climb. Celebrate. Repeat."}
          </p>            
        </div>
      </section>
    </>
  );
}
